apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd  # Assumes ArgoCD in 'argocd' namespace
  # Labels: e.g., app.kubernetes.io/name: cert-manager
spec:
  project: default  # Dedicated project recommended
  source:
    repoURL: https://charts.jetstack.io  # Official Helm repo
    chart: cert-manager
    targetRevision: 1.15.3  # Latest stable; pin for production
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true  # Install CRDs with the chart for idempotency
        replicaCount: 2
        image:
          repository: quay.io/jetstack/cert-manager-controller
          pullPolicy: IfNotPresent
          # tag: 1.15.3  # Managed by chart version
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        # Webhook configuration
        webhook:
          enabled: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 128Mi
        global:
          podSecurityPolicy:
            enabled: false  # Deprecated in newer K8s
          leaderElection:
            namespace: cert-manager  # Dedicated namespace
        extraArgs:
          - --enable-metrics=true
        metrics:
          serviceMonitor:
            enabled: true  # For Prometheus
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 2000
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        rbac:
          create: true
        serviceAccount:
          create: true
          annotations: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager  # Dedicated namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    # Sync waves: CRDs first if needed, but installCRDs=true handles
  # info: {}  # Optional: Add post-sync hooks for ClusterIssuer
  # Assumptions: AWS EKS; post-install: Create ClusterIssuer for Let's Encrypt as noted in values.yaml