apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd  # Assumes ArgoCD in 'argocd' namespace
spec:
  project: default  # Dedicated project recommended
  sources:
  - repoURL: https://charts.jetstack.io  # Official Helm repo
    chart: cert-manager
    targetRevision: 1.15.3  # Latest stable; pin for production
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true  # Install CRDs with the chart for idempotency
        replicaCount: 2
        image:
          repository: quay.io/jetstack/cert-manager-controller
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        webhook:
          enabled: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 128Mi
        global:
          podSecurityPolicy:
            enabled: false  # Deprecated in newer K8s
          leaderElection:
            namespace: cert-manager  # Dedicated namespace
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 2000
        rbac:
          create: true
        serviceAccount:
          create: true
          name: cert-manager
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::704855531002:role/eks-llm-cert-manager"
  - repoURL: https://github.com/andrewdeweever/eks_llm
    targetRevision: HEAD
    path: cert-manager-resources
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager  # Primary namespace for the app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=true