apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: andrew.deweever@bscanalytics.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          route53: 
            region: us-west-2